// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchangeRate.proto

package com.gash.application.grpc.exchangerate;

public final class ExchangeRate {
  private ExchangeRate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gash_application_grpc_exchangerate_ExchangeRateReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gash_application_grpc_exchangerate_ExchangeRateReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gash_application_grpc_exchangerate_ExchangeRateResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gash_application_grpc_exchangerate_ExchangeRateResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022exchangeRate.proto\022&com.gash.applicati" +
      "on.grpc.exchangerate\"E\n\017ExchangeRateReq\022" +
      "\024\n\014currencyCode\030\001 \001(\t\022\034\n\024exchangeCurrenc" +
      "yCode\030\002 \001(\t\"\243\001\n\020ExchangeRateResp\022\017\n\007msgC" +
      "ode\030\001 \001(\t\022\024\n\014currencyCode\030\002 \001(\t\022\034\n\024excha" +
      "ngeCurrencyCode\030\003 \001(\t\022\r\n\005price\030\004 \001(\t\022\024\n\014" +
      "priceHigh24h\030\005 \001(\t\022\023\n\013priceLow24h\030\006 \001(\t\022" +
      "\020\n\010unixTime\030\007 \001(\0032\243\001\n\030ExchangeRateQueryS" +
      "ervice\022\206\001\n\017getExchangeRate\0227.com.gash.ap" +
      "plication.grpc.exchangerate.ExchangeRate" +
      "Req\0328.com.gash.application.grpc.exchange" +
      "rate.ExchangeRateResp\"\000B-\n&com.gash.appl" +
      "ication.grpc.exchangerateP\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_gash_application_grpc_exchangerate_ExchangeRateReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gash_application_grpc_exchangerate_ExchangeRateReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gash_application_grpc_exchangerate_ExchangeRateReq_descriptor,
        new String[] { "CurrencyCode", "ExchangeCurrencyCode", });
    internal_static_com_gash_application_grpc_exchangerate_ExchangeRateResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gash_application_grpc_exchangerate_ExchangeRateResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gash_application_grpc_exchangerate_ExchangeRateResp_descriptor,
        new String[] { "MsgCode", "CurrencyCode", "ExchangeCurrencyCode", "Price", "PriceHigh24H", "PriceLow24H", "UnixTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
