// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchangeRate.proto

package com.gash.application.grpc.exchangerate;

/**
 * <pre>
 * The request message containing the user's name.
 * </pre>
 *
 * Protobuf type {@code com.gash.application.grpc.exchangerate.ExchangeRateReq}
 */
public  final class ExchangeRateReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gash.application.grpc.exchangerate.ExchangeRateReq)
    ExchangeRateReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExchangeRateReq.newBuilder() to construct.
  private ExchangeRateReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExchangeRateReq() {
    currencyCode_ = "";
    exchangeCurrencyCode_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExchangeRateReq();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExchangeRateReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            currencyCode_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            exchangeCurrencyCode_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gash.application.grpc.exchangerate.ExchangeRate.internal_static_com_gash_application_grpc_exchangerate_ExchangeRateReq_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gash.application.grpc.exchangerate.ExchangeRate.internal_static_com_gash_application_grpc_exchangerate_ExchangeRateReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gash.application.grpc.exchangerate.ExchangeRateReq.class, com.gash.application.grpc.exchangerate.ExchangeRateReq.Builder.class);
  }

  public static final int CURRENCYCODE_FIELD_NUMBER = 1;
  private volatile Object currencyCode_;
  /**
   * <code>string currencyCode = 1;</code>
   * @return The currencyCode.
   */
  public String getCurrencyCode() {
    Object ref = currencyCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      currencyCode_ = s;
      return s;
    }
  }
  /**
   * <code>string currencyCode = 1;</code>
   * @return The bytes for currencyCode.
   */
  public com.google.protobuf.ByteString
      getCurrencyCodeBytes() {
    Object ref = currencyCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      currencyCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXCHANGECURRENCYCODE_FIELD_NUMBER = 2;
  private volatile Object exchangeCurrencyCode_;
  /**
   * <code>string exchangeCurrencyCode = 2;</code>
   * @return The exchangeCurrencyCode.
   */
  public String getExchangeCurrencyCode() {
    Object ref = exchangeCurrencyCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      exchangeCurrencyCode_ = s;
      return s;
    }
  }
  /**
   * <code>string exchangeCurrencyCode = 2;</code>
   * @return The bytes for exchangeCurrencyCode.
   */
  public com.google.protobuf.ByteString
      getExchangeCurrencyCodeBytes() {
    Object ref = exchangeCurrencyCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      exchangeCurrencyCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCurrencyCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currencyCode_);
    }
    if (!getExchangeCurrencyCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, exchangeCurrencyCode_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCurrencyCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currencyCode_);
    }
    if (!getExchangeCurrencyCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, exchangeCurrencyCode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gash.application.grpc.exchangerate.ExchangeRateReq)) {
      return super.equals(obj);
    }
    com.gash.application.grpc.exchangerate.ExchangeRateReq other = (com.gash.application.grpc.exchangerate.ExchangeRateReq) obj;

    if (!getCurrencyCode()
        .equals(other.getCurrencyCode())) return false;
    if (!getExchangeCurrencyCode()
        .equals(other.getExchangeCurrencyCode())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENCYCODE_FIELD_NUMBER;
    hash = (53 * hash) + getCurrencyCode().hashCode();
    hash = (37 * hash) + EXCHANGECURRENCYCODE_FIELD_NUMBER;
    hash = (53 * hash) + getExchangeCurrencyCode().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gash.application.grpc.exchangerate.ExchangeRateReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gash.application.grpc.exchangerate.ExchangeRateReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gash.application.grpc.exchangerate.ExchangeRateReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gash.application.grpc.exchangerate.ExchangeRateReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gash.application.grpc.exchangerate.ExchangeRateReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gash.application.grpc.exchangerate.ExchangeRateReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gash.application.grpc.exchangerate.ExchangeRateReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gash.application.grpc.exchangerate.ExchangeRateReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gash.application.grpc.exchangerate.ExchangeRateReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gash.application.grpc.exchangerate.ExchangeRateReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gash.application.grpc.exchangerate.ExchangeRateReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gash.application.grpc.exchangerate.ExchangeRateReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gash.application.grpc.exchangerate.ExchangeRateReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The request message containing the user's name.
   * </pre>
   *
   * Protobuf type {@code com.gash.application.grpc.exchangerate.ExchangeRateReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gash.application.grpc.exchangerate.ExchangeRateReq)
      com.gash.application.grpc.exchangerate.ExchangeRateReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gash.application.grpc.exchangerate.ExchangeRate.internal_static_com_gash_application_grpc_exchangerate_ExchangeRateReq_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gash.application.grpc.exchangerate.ExchangeRate.internal_static_com_gash_application_grpc_exchangerate_ExchangeRateReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gash.application.grpc.exchangerate.ExchangeRateReq.class, com.gash.application.grpc.exchangerate.ExchangeRateReq.Builder.class);
    }

    // Construct using com.gash.application.grpc.exchangerate.ExchangeRateReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      currencyCode_ = "";

      exchangeCurrencyCode_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gash.application.grpc.exchangerate.ExchangeRate.internal_static_com_gash_application_grpc_exchangerate_ExchangeRateReq_descriptor;
    }

    @Override
    public com.gash.application.grpc.exchangerate.ExchangeRateReq getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public com.gash.application.grpc.exchangerate.ExchangeRateReq build() {
      com.gash.application.grpc.exchangerate.ExchangeRateReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.gash.application.grpc.exchangerate.ExchangeRateReq buildPartial() {
      com.gash.application.grpc.exchangerate.ExchangeRateReq result = new com.gash.application.grpc.exchangerate.ExchangeRateReq(this);
      result.currencyCode_ = currencyCode_;
      result.exchangeCurrencyCode_ = exchangeCurrencyCode_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gash.application.grpc.exchangerate.ExchangeRateReq) {
        return mergeFrom((com.gash.application.grpc.exchangerate.ExchangeRateReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gash.application.grpc.exchangerate.ExchangeRateReq other) {
      if (other == getDefaultInstance()) return this;
      if (!other.getCurrencyCode().isEmpty()) {
        currencyCode_ = other.currencyCode_;
        onChanged();
      }
      if (!other.getExchangeCurrencyCode().isEmpty()) {
        exchangeCurrencyCode_ = other.exchangeCurrencyCode_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gash.application.grpc.exchangerate.ExchangeRateReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gash.application.grpc.exchangerate.ExchangeRateReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object currencyCode_ = "";
    /**
     * <code>string currencyCode = 1;</code>
     * @return The currencyCode.
     */
    public String getCurrencyCode() {
      Object ref = currencyCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        currencyCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string currencyCode = 1;</code>
     * @return The bytes for currencyCode.
     */
    public com.google.protobuf.ByteString
        getCurrencyCodeBytes() {
      Object ref = currencyCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        currencyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string currencyCode = 1;</code>
     * @param value The currencyCode to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currencyCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string currencyCode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrencyCode() {
      
      currencyCode_ = getDefaultInstance().getCurrencyCode();
      onChanged();
      return this;
    }
    /**
     * <code>string currencyCode = 1;</code>
     * @param value The bytes for currencyCode to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currencyCode_ = value;
      onChanged();
      return this;
    }

    private Object exchangeCurrencyCode_ = "";
    /**
     * <code>string exchangeCurrencyCode = 2;</code>
     * @return The exchangeCurrencyCode.
     */
    public String getExchangeCurrencyCode() {
      Object ref = exchangeCurrencyCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        exchangeCurrencyCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string exchangeCurrencyCode = 2;</code>
     * @return The bytes for exchangeCurrencyCode.
     */
    public com.google.protobuf.ByteString
        getExchangeCurrencyCodeBytes() {
      Object ref = exchangeCurrencyCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        exchangeCurrencyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string exchangeCurrencyCode = 2;</code>
     * @param value The exchangeCurrencyCode to set.
     * @return This builder for chaining.
     */
    public Builder setExchangeCurrencyCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      exchangeCurrencyCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string exchangeCurrencyCode = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExchangeCurrencyCode() {
      
      exchangeCurrencyCode_ = getDefaultInstance().getExchangeCurrencyCode();
      onChanged();
      return this;
    }
    /**
     * <code>string exchangeCurrencyCode = 2;</code>
     * @param value The bytes for exchangeCurrencyCode to set.
     * @return This builder for chaining.
     */
    public Builder setExchangeCurrencyCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      exchangeCurrencyCode_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.gash.application.grpc.exchangerate.ExchangeRateReq)
  }

  // @@protoc_insertion_point(class_scope:com.gash.application.grpc.exchangerate.ExchangeRateReq)
  private static final com.gash.application.grpc.exchangerate.ExchangeRateReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gash.application.grpc.exchangerate.ExchangeRateReq();
  }

  public static com.gash.application.grpc.exchangerate.ExchangeRateReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExchangeRateReq>
      PARSER = new com.google.protobuf.AbstractParser<ExchangeRateReq>() {
    @Override
    public ExchangeRateReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExchangeRateReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExchangeRateReq> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ExchangeRateReq> getParserForType() {
    return PARSER;
  }

  @Override
  public com.gash.application.grpc.exchangerate.ExchangeRateReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

