// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchangeRate.proto

package com.gash.application.grpc.exchangerate;

public interface ExchangeRateRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gash.application.grpc.exchangerate.ExchangeRateResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 000000 成功 99999 失敗
   * </pre>
   *
   * <code>string msgCode = 1;</code>
   * @return The msgCode.
   */
  String getMsgCode();
  /**
   * <pre>
   * 000000 成功 99999 失敗
   * </pre>
   *
   * <code>string msgCode = 1;</code>
   * @return The bytes for msgCode.
   */
  com.google.protobuf.ByteString
      getMsgCodeBytes();

  /**
   * <code>string currencyCode = 2;</code>
   * @return The currencyCode.
   */
  String getCurrencyCode();
  /**
   * <code>string currencyCode = 2;</code>
   * @return The bytes for currencyCode.
   */
  com.google.protobuf.ByteString
      getCurrencyCodeBytes();

  /**
   * <code>string exchangeCurrencyCode = 3;</code>
   * @return The exchangeCurrencyCode.
   */
  String getExchangeCurrencyCode();
  /**
   * <code>string exchangeCurrencyCode = 3;</code>
   * @return The bytes for exchangeCurrencyCode.
   */
  com.google.protobuf.ByteString
      getExchangeCurrencyCodeBytes();

  /**
   * <code>string price = 4;</code>
   * @return The price.
   */
  String getPrice();
  /**
   * <code>string price = 4;</code>
   * @return The bytes for price.
   */
  com.google.protobuf.ByteString
      getPriceBytes();

  /**
   * <code>string priceHigh24h = 5;</code>
   * @return The priceHigh24h.
   */
  String getPriceHigh24H();
  /**
   * <code>string priceHigh24h = 5;</code>
   * @return The bytes for priceHigh24h.
   */
  com.google.protobuf.ByteString
      getPriceHigh24HBytes();

  /**
   * <code>string priceLow24h = 6;</code>
   * @return The priceLow24h.
   */
  String getPriceLow24H();
  /**
   * <code>string priceLow24h = 6;</code>
   * @return The bytes for priceLow24h.
   */
  com.google.protobuf.ByteString
      getPriceLow24HBytes();

  /**
   * <code>int64 unixTime = 7;</code>
   * @return The unixTime.
   */
  long getUnixTime();
}
