// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchangeRate.proto

package com.gash.application.grpc.exchangerate;

/**
 * <pre>
 * The greeting service definition.
 * </pre>
 *
 * Protobuf service {@code com.gash.application.grpc.exchangerate.ExchangeRateQueryService}
 */
public  abstract class ExchangeRateQueryService
    implements com.google.protobuf.Service {
  protected ExchangeRateQueryService() {}

  public interface Interface {
    /**
     * <pre>
     * Sends a greeting
     * </pre>
     *
     * <code>rpc getExchangeRate(.com.gash.application.grpc.exchangerate.ExchangeRateReq) returns (.com.gash.application.grpc.exchangerate.ExchangeRateResp);</code>
     */
    public abstract void getExchangeRate(
        com.google.protobuf.RpcController controller,
        com.gash.application.grpc.exchangerate.ExchangeRateReq request,
        com.google.protobuf.RpcCallback<com.gash.application.grpc.exchangerate.ExchangeRateResp> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new ExchangeRateQueryService() {
      @Override
      public  void getExchangeRate(
          com.google.protobuf.RpcController controller,
          com.gash.application.grpc.exchangerate.ExchangeRateReq request,
          com.google.protobuf.RpcCallback<com.gash.application.grpc.exchangerate.ExchangeRateResp> done) {
        impl.getExchangeRate(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.getExchangeRate(controller, (com.gash.application.grpc.exchangerate.ExchangeRateReq)request);
          default:
            throw new AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.gash.application.grpc.exchangerate.ExchangeRateReq.getDefaultInstance();
          default:
            throw new AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.gash.application.grpc.exchangerate.ExchangeRateResp.getDefaultInstance();
          default:
            throw new AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <pre>
   * Sends a greeting
   * </pre>
   *
   * <code>rpc getExchangeRate(.com.gash.application.grpc.exchangerate.ExchangeRateReq) returns (.com.gash.application.grpc.exchangerate.ExchangeRateResp);</code>
   */
  public abstract void getExchangeRate(
      com.google.protobuf.RpcController controller,
      com.gash.application.grpc.exchangerate.ExchangeRateReq request,
      com.google.protobuf.RpcCallback<com.gash.application.grpc.exchangerate.ExchangeRateResp> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.gash.application.grpc.exchangerate.ExchangeRate.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.getExchangeRate(controller, (com.gash.application.grpc.exchangerate.ExchangeRateReq)request,
          com.google.protobuf.RpcUtil.<com.gash.application.grpc.exchangerate.ExchangeRateResp>specializeCallback(
            done));
        return;
      default:
        throw new AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.gash.application.grpc.exchangerate.ExchangeRateReq.getDefaultInstance();
      default:
        throw new AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.gash.application.grpc.exchangerate.ExchangeRateResp.getDefaultInstance();
      default:
        throw new AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.gash.application.grpc.exchangerate.ExchangeRateQueryService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void getExchangeRate(
        com.google.protobuf.RpcController controller,
        com.gash.application.grpc.exchangerate.ExchangeRateReq request,
        com.google.protobuf.RpcCallback<com.gash.application.grpc.exchangerate.ExchangeRateResp> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.gash.application.grpc.exchangerate.ExchangeRateResp.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.gash.application.grpc.exchangerate.ExchangeRateResp.class,
          com.gash.application.grpc.exchangerate.ExchangeRateResp.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.gash.application.grpc.exchangerate.ExchangeRateResp getExchangeRate(
        com.google.protobuf.RpcController controller,
        com.gash.application.grpc.exchangerate.ExchangeRateReq request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.gash.application.grpc.exchangerate.ExchangeRateResp getExchangeRate(
        com.google.protobuf.RpcController controller,
        com.gash.application.grpc.exchangerate.ExchangeRateReq request)
        throws com.google.protobuf.ServiceException {
      return (com.gash.application.grpc.exchangerate.ExchangeRateResp) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.gash.application.grpc.exchangerate.ExchangeRateResp.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:com.gash.application.grpc.exchangerate.ExchangeRateQueryService)
}

