server:
  port: 8080
  servlet:
    context-path: /frizo
  shutdown: graceful

spring:
  config:
    import: classpath:/settings/dev-setting.yml

  cache:
    type: REDIS
  redis:
    database: 0
    ##alpha
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 30
        max-idle: 30
        max-wait: -1
        min-idle: 0
    timeout: 3000 #mini second
  lifecycle:
    timeout-per-shutdown-phase: 60s

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.gash: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate: ERROR
    com.redis.catch: DEBUG





