// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExchangeRate.proto

package com.frizo.grpc.api;

public final class ExchangeRate {
  private ExchangeRate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExchangeRateReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gash.grpc.lib.ExchangeRateReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string currencyCode = 1;</code>
     * @return The currencyCode.
     */
    java.lang.String getCurrencyCode();
    /**
     * <code>string currencyCode = 1;</code>
     * @return The bytes for currencyCode.
     */
    com.google.protobuf.ByteString
        getCurrencyCodeBytes();

    /**
     * <code>string exchangeCurrencyCode = 2;</code>
     * @return The exchangeCurrencyCode.
     */
    java.lang.String getExchangeCurrencyCode();
    /**
     * <code>string exchangeCurrencyCode = 2;</code>
     * @return The bytes for exchangeCurrencyCode.
     */
    com.google.protobuf.ByteString
        getExchangeCurrencyCodeBytes();
  }
  /**
   * <pre>
   * The request message containing the user's name.
   * </pre>
   *
   * Protobuf type {@code com.gash.grpc.lib.ExchangeRateReq}
   */
  public  static final class ExchangeRateReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gash.grpc.lib.ExchangeRateReq)
      ExchangeRateReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExchangeRateReq.newBuilder() to construct.
    private ExchangeRateReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExchangeRateReq() {
      currencyCode_ = "";
      exchangeCurrencyCode_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExchangeRateReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExchangeRateReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              currencyCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              exchangeCurrencyCode_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.frizo.grpc.api.ExchangeRate.internal_static_com_gash_grpc_lib_ExchangeRateReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.frizo.grpc.api.ExchangeRate.internal_static_com_gash_grpc_lib_ExchangeRateReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.frizo.grpc.api.ExchangeRate.ExchangeRateReq.class, com.frizo.grpc.api.ExchangeRate.ExchangeRateReq.Builder.class);
    }

    public static final int CURRENCYCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object currencyCode_;
    /**
     * <code>string currencyCode = 1;</code>
     * @return The currencyCode.
     */
    public java.lang.String getCurrencyCode() {
      java.lang.Object ref = currencyCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currencyCode_ = s;
        return s;
      }
    }
    /**
     * <code>string currencyCode = 1;</code>
     * @return The bytes for currencyCode.
     */
    public com.google.protobuf.ByteString
        getCurrencyCodeBytes() {
      java.lang.Object ref = currencyCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currencyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCHANGECURRENCYCODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object exchangeCurrencyCode_;
    /**
     * <code>string exchangeCurrencyCode = 2;</code>
     * @return The exchangeCurrencyCode.
     */
    public java.lang.String getExchangeCurrencyCode() {
      java.lang.Object ref = exchangeCurrencyCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exchangeCurrencyCode_ = s;
        return s;
      }
    }
    /**
     * <code>string exchangeCurrencyCode = 2;</code>
     * @return The bytes for exchangeCurrencyCode.
     */
    public com.google.protobuf.ByteString
        getExchangeCurrencyCodeBytes() {
      java.lang.Object ref = exchangeCurrencyCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exchangeCurrencyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCurrencyCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currencyCode_);
      }
      if (!getExchangeCurrencyCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, exchangeCurrencyCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCurrencyCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currencyCode_);
      }
      if (!getExchangeCurrencyCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, exchangeCurrencyCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.frizo.grpc.api.ExchangeRate.ExchangeRateReq)) {
        return super.equals(obj);
      }
      com.frizo.grpc.api.ExchangeRate.ExchangeRateReq other = (com.frizo.grpc.api.ExchangeRate.ExchangeRateReq) obj;

      if (!getCurrencyCode()
          .equals(other.getCurrencyCode())) return false;
      if (!getExchangeCurrencyCode()
          .equals(other.getExchangeCurrencyCode())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENCYCODE_FIELD_NUMBER;
      hash = (53 * hash) + getCurrencyCode().hashCode();
      hash = (37 * hash) + EXCHANGECURRENCYCODE_FIELD_NUMBER;
      hash = (53 * hash) + getExchangeCurrencyCode().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.frizo.grpc.api.ExchangeRate.ExchangeRateReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request message containing the user's name.
     * </pre>
     *
     * Protobuf type {@code com.gash.grpc.lib.ExchangeRateReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gash.grpc.lib.ExchangeRateReq)
        com.frizo.grpc.api.ExchangeRate.ExchangeRateReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.frizo.grpc.api.ExchangeRate.internal_static_com_gash_grpc_lib_ExchangeRateReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.frizo.grpc.api.ExchangeRate.internal_static_com_gash_grpc_lib_ExchangeRateReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.frizo.grpc.api.ExchangeRate.ExchangeRateReq.class, com.frizo.grpc.api.ExchangeRate.ExchangeRateReq.Builder.class);
      }

      // Construct using com.frizo.grpc.api.ExchangeRate.ExchangeRateReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currencyCode_ = "";

        exchangeCurrencyCode_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.frizo.grpc.api.ExchangeRate.internal_static_com_gash_grpc_lib_ExchangeRateReq_descriptor;
      }

      @java.lang.Override
      public com.frizo.grpc.api.ExchangeRate.ExchangeRateReq getDefaultInstanceForType() {
        return com.frizo.grpc.api.ExchangeRate.ExchangeRateReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.frizo.grpc.api.ExchangeRate.ExchangeRateReq build() {
        com.frizo.grpc.api.ExchangeRate.ExchangeRateReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.frizo.grpc.api.ExchangeRate.ExchangeRateReq buildPartial() {
        com.frizo.grpc.api.ExchangeRate.ExchangeRateReq result = new com.frizo.grpc.api.ExchangeRate.ExchangeRateReq(this);
        result.currencyCode_ = currencyCode_;
        result.exchangeCurrencyCode_ = exchangeCurrencyCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.frizo.grpc.api.ExchangeRate.ExchangeRateReq) {
          return mergeFrom((com.frizo.grpc.api.ExchangeRate.ExchangeRateReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.frizo.grpc.api.ExchangeRate.ExchangeRateReq other) {
        if (other == com.frizo.grpc.api.ExchangeRate.ExchangeRateReq.getDefaultInstance()) return this;
        if (!other.getCurrencyCode().isEmpty()) {
          currencyCode_ = other.currencyCode_;
          onChanged();
        }
        if (!other.getExchangeCurrencyCode().isEmpty()) {
          exchangeCurrencyCode_ = other.exchangeCurrencyCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.frizo.grpc.api.ExchangeRate.ExchangeRateReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.frizo.grpc.api.ExchangeRate.ExchangeRateReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object currencyCode_ = "";
      /**
       * <code>string currencyCode = 1;</code>
       * @return The currencyCode.
       */
      public java.lang.String getCurrencyCode() {
        java.lang.Object ref = currencyCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currencyCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currencyCode = 1;</code>
       * @return The bytes for currencyCode.
       */
      public com.google.protobuf.ByteString
          getCurrencyCodeBytes() {
        java.lang.Object ref = currencyCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currencyCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currencyCode = 1;</code>
       * @param value The currencyCode to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currencyCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currencyCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrencyCode() {
        
        currencyCode_ = getDefaultInstance().getCurrencyCode();
        onChanged();
        return this;
      }
      /**
       * <code>string currencyCode = 1;</code>
       * @param value The bytes for currencyCode to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currencyCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object exchangeCurrencyCode_ = "";
      /**
       * <code>string exchangeCurrencyCode = 2;</code>
       * @return The exchangeCurrencyCode.
       */
      public java.lang.String getExchangeCurrencyCode() {
        java.lang.Object ref = exchangeCurrencyCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          exchangeCurrencyCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string exchangeCurrencyCode = 2;</code>
       * @return The bytes for exchangeCurrencyCode.
       */
      public com.google.protobuf.ByteString
          getExchangeCurrencyCodeBytes() {
        java.lang.Object ref = exchangeCurrencyCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exchangeCurrencyCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string exchangeCurrencyCode = 2;</code>
       * @param value The exchangeCurrencyCode to set.
       * @return This builder for chaining.
       */
      public Builder setExchangeCurrencyCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        exchangeCurrencyCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string exchangeCurrencyCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearExchangeCurrencyCode() {
        
        exchangeCurrencyCode_ = getDefaultInstance().getExchangeCurrencyCode();
        onChanged();
        return this;
      }
      /**
       * <code>string exchangeCurrencyCode = 2;</code>
       * @param value The bytes for exchangeCurrencyCode to set.
       * @return This builder for chaining.
       */
      public Builder setExchangeCurrencyCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        exchangeCurrencyCode_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.gash.grpc.lib.ExchangeRateReq)
    }

    // @@protoc_insertion_point(class_scope:com.gash.grpc.lib.ExchangeRateReq)
    private static final com.frizo.grpc.api.ExchangeRate.ExchangeRateReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.frizo.grpc.api.ExchangeRate.ExchangeRateReq();
    }

    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExchangeRateReq>
        PARSER = new com.google.protobuf.AbstractParser<ExchangeRateReq>() {
      @java.lang.Override
      public ExchangeRateReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExchangeRateReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExchangeRateReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExchangeRateReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.frizo.grpc.api.ExchangeRate.ExchangeRateReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExchangeRateRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gash.grpc.lib.ExchangeRateResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 000000 成功 99999 失敗
     * </pre>
     *
     * <code>string msgCode = 1;</code>
     * @return The msgCode.
     */
    java.lang.String getMsgCode();
    /**
     * <pre>
     * 000000 成功 99999 失敗
     * </pre>
     *
     * <code>string msgCode = 1;</code>
     * @return The bytes for msgCode.
     */
    com.google.protobuf.ByteString
        getMsgCodeBytes();

    /**
     * <code>string currencyCode = 2;</code>
     * @return The currencyCode.
     */
    java.lang.String getCurrencyCode();
    /**
     * <code>string currencyCode = 2;</code>
     * @return The bytes for currencyCode.
     */
    com.google.protobuf.ByteString
        getCurrencyCodeBytes();

    /**
     * <code>string exchangeCurrencyCode = 3;</code>
     * @return The exchangeCurrencyCode.
     */
    java.lang.String getExchangeCurrencyCode();
    /**
     * <code>string exchangeCurrencyCode = 3;</code>
     * @return The bytes for exchangeCurrencyCode.
     */
    com.google.protobuf.ByteString
        getExchangeCurrencyCodeBytes();

    /**
     * <code>string price = 4;</code>
     * @return The price.
     */
    java.lang.String getPrice();
    /**
     * <code>string price = 4;</code>
     * @return The bytes for price.
     */
    com.google.protobuf.ByteString
        getPriceBytes();

    /**
     * <code>string priceHigh24h = 5;</code>
     * @return The priceHigh24h.
     */
    java.lang.String getPriceHigh24H();
    /**
     * <code>string priceHigh24h = 5;</code>
     * @return The bytes for priceHigh24h.
     */
    com.google.protobuf.ByteString
        getPriceHigh24HBytes();

    /**
     * <code>string priceLow24h = 6;</code>
     * @return The priceLow24h.
     */
    java.lang.String getPriceLow24H();
    /**
     * <code>string priceLow24h = 6;</code>
     * @return The bytes for priceLow24h.
     */
    com.google.protobuf.ByteString
        getPriceLow24HBytes();

    /**
     * <code>int64 unixTime = 7;</code>
     * @return The unixTime.
     */
    long getUnixTime();
  }
  /**
   * <pre>
   * The response message containing the greetings
   * </pre>
   *
   * Protobuf type {@code com.gash.grpc.lib.ExchangeRateResp}
   */
  public  static final class ExchangeRateResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gash.grpc.lib.ExchangeRateResp)
      ExchangeRateRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExchangeRateResp.newBuilder() to construct.
    private ExchangeRateResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExchangeRateResp() {
      msgCode_ = "";
      currencyCode_ = "";
      exchangeCurrencyCode_ = "";
      price_ = "";
      priceHigh24H_ = "";
      priceLow24H_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExchangeRateResp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExchangeRateResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              msgCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              currencyCode_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              exchangeCurrencyCode_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              price_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              priceHigh24H_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              priceLow24H_ = s;
              break;
            }
            case 56: {

              unixTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.frizo.grpc.api.ExchangeRate.internal_static_com_gash_grpc_lib_ExchangeRateResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.frizo.grpc.api.ExchangeRate.internal_static_com_gash_grpc_lib_ExchangeRateResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.frizo.grpc.api.ExchangeRate.ExchangeRateResp.class, com.frizo.grpc.api.ExchangeRate.ExchangeRateResp.Builder.class);
    }

    public static final int MSGCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object msgCode_;
    /**
     * <pre>
     * 000000 成功 99999 失敗
     * </pre>
     *
     * <code>string msgCode = 1;</code>
     * @return The msgCode.
     */
    public java.lang.String getMsgCode() {
      java.lang.Object ref = msgCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 000000 成功 99999 失敗
     * </pre>
     *
     * <code>string msgCode = 1;</code>
     * @return The bytes for msgCode.
     */
    public com.google.protobuf.ByteString
        getMsgCodeBytes() {
      java.lang.Object ref = msgCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENCYCODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object currencyCode_;
    /**
     * <code>string currencyCode = 2;</code>
     * @return The currencyCode.
     */
    public java.lang.String getCurrencyCode() {
      java.lang.Object ref = currencyCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currencyCode_ = s;
        return s;
      }
    }
    /**
     * <code>string currencyCode = 2;</code>
     * @return The bytes for currencyCode.
     */
    public com.google.protobuf.ByteString
        getCurrencyCodeBytes() {
      java.lang.Object ref = currencyCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currencyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCHANGECURRENCYCODE_FIELD_NUMBER = 3;
    private volatile java.lang.Object exchangeCurrencyCode_;
    /**
     * <code>string exchangeCurrencyCode = 3;</code>
     * @return The exchangeCurrencyCode.
     */
    public java.lang.String getExchangeCurrencyCode() {
      java.lang.Object ref = exchangeCurrencyCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exchangeCurrencyCode_ = s;
        return s;
      }
    }
    /**
     * <code>string exchangeCurrencyCode = 3;</code>
     * @return The bytes for exchangeCurrencyCode.
     */
    public com.google.protobuf.ByteString
        getExchangeCurrencyCodeBytes() {
      java.lang.Object ref = exchangeCurrencyCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exchangeCurrencyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 4;
    private volatile java.lang.Object price_;
    /**
     * <code>string price = 4;</code>
     * @return The price.
     */
    public java.lang.String getPrice() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        price_ = s;
        return s;
      }
    }
    /**
     * <code>string price = 4;</code>
     * @return The bytes for price.
     */
    public com.google.protobuf.ByteString
        getPriceBytes() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICEHIGH24H_FIELD_NUMBER = 5;
    private volatile java.lang.Object priceHigh24H_;
    /**
     * <code>string priceHigh24h = 5;</code>
     * @return The priceHigh24h.
     */
    public java.lang.String getPriceHigh24H() {
      java.lang.Object ref = priceHigh24H_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        priceHigh24H_ = s;
        return s;
      }
    }
    /**
     * <code>string priceHigh24h = 5;</code>
     * @return The bytes for priceHigh24h.
     */
    public com.google.protobuf.ByteString
        getPriceHigh24HBytes() {
      java.lang.Object ref = priceHigh24H_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        priceHigh24H_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICELOW24H_FIELD_NUMBER = 6;
    private volatile java.lang.Object priceLow24H_;
    /**
     * <code>string priceLow24h = 6;</code>
     * @return The priceLow24h.
     */
    public java.lang.String getPriceLow24H() {
      java.lang.Object ref = priceLow24H_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        priceLow24H_ = s;
        return s;
      }
    }
    /**
     * <code>string priceLow24h = 6;</code>
     * @return The bytes for priceLow24h.
     */
    public com.google.protobuf.ByteString
        getPriceLow24HBytes() {
      java.lang.Object ref = priceLow24H_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        priceLow24H_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UNIXTIME_FIELD_NUMBER = 7;
    private long unixTime_;
    /**
     * <code>int64 unixTime = 7;</code>
     * @return The unixTime.
     */
    public long getUnixTime() {
      return unixTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMsgCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgCode_);
      }
      if (!getCurrencyCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, currencyCode_);
      }
      if (!getExchangeCurrencyCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, exchangeCurrencyCode_);
      }
      if (!getPriceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, price_);
      }
      if (!getPriceHigh24HBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, priceHigh24H_);
      }
      if (!getPriceLow24HBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, priceLow24H_);
      }
      if (unixTime_ != 0L) {
        output.writeInt64(7, unixTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMsgCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgCode_);
      }
      if (!getCurrencyCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, currencyCode_);
      }
      if (!getExchangeCurrencyCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, exchangeCurrencyCode_);
      }
      if (!getPriceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, price_);
      }
      if (!getPriceHigh24HBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, priceHigh24H_);
      }
      if (!getPriceLow24HBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, priceLow24H_);
      }
      if (unixTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, unixTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.frizo.grpc.api.ExchangeRate.ExchangeRateResp)) {
        return super.equals(obj);
      }
      com.frizo.grpc.api.ExchangeRate.ExchangeRateResp other = (com.frizo.grpc.api.ExchangeRate.ExchangeRateResp) obj;

      if (!getMsgCode()
          .equals(other.getMsgCode())) return false;
      if (!getCurrencyCode()
          .equals(other.getCurrencyCode())) return false;
      if (!getExchangeCurrencyCode()
          .equals(other.getExchangeCurrencyCode())) return false;
      if (!getPrice()
          .equals(other.getPrice())) return false;
      if (!getPriceHigh24H()
          .equals(other.getPriceHigh24H())) return false;
      if (!getPriceLow24H()
          .equals(other.getPriceLow24H())) return false;
      if (getUnixTime()
          != other.getUnixTime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGCODE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgCode().hashCode();
      hash = (37 * hash) + CURRENCYCODE_FIELD_NUMBER;
      hash = (53 * hash) + getCurrencyCode().hashCode();
      hash = (37 * hash) + EXCHANGECURRENCYCODE_FIELD_NUMBER;
      hash = (53 * hash) + getExchangeCurrencyCode().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice().hashCode();
      hash = (37 * hash) + PRICEHIGH24H_FIELD_NUMBER;
      hash = (53 * hash) + getPriceHigh24H().hashCode();
      hash = (37 * hash) + PRICELOW24H_FIELD_NUMBER;
      hash = (53 * hash) + getPriceLow24H().hashCode();
      hash = (37 * hash) + UNIXTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUnixTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.frizo.grpc.api.ExchangeRate.ExchangeRateResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The response message containing the greetings
     * </pre>
     *
     * Protobuf type {@code com.gash.grpc.lib.ExchangeRateResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gash.grpc.lib.ExchangeRateResp)
        com.frizo.grpc.api.ExchangeRate.ExchangeRateRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.frizo.grpc.api.ExchangeRate.internal_static_com_gash_grpc_lib_ExchangeRateResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.frizo.grpc.api.ExchangeRate.internal_static_com_gash_grpc_lib_ExchangeRateResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.frizo.grpc.api.ExchangeRate.ExchangeRateResp.class, com.frizo.grpc.api.ExchangeRate.ExchangeRateResp.Builder.class);
      }

      // Construct using com.frizo.grpc.api.ExchangeRate.ExchangeRateResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgCode_ = "";

        currencyCode_ = "";

        exchangeCurrencyCode_ = "";

        price_ = "";

        priceHigh24H_ = "";

        priceLow24H_ = "";

        unixTime_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.frizo.grpc.api.ExchangeRate.internal_static_com_gash_grpc_lib_ExchangeRateResp_descriptor;
      }

      @java.lang.Override
      public com.frizo.grpc.api.ExchangeRate.ExchangeRateResp getDefaultInstanceForType() {
        return com.frizo.grpc.api.ExchangeRate.ExchangeRateResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.frizo.grpc.api.ExchangeRate.ExchangeRateResp build() {
        com.frizo.grpc.api.ExchangeRate.ExchangeRateResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.frizo.grpc.api.ExchangeRate.ExchangeRateResp buildPartial() {
        com.frizo.grpc.api.ExchangeRate.ExchangeRateResp result = new com.frizo.grpc.api.ExchangeRate.ExchangeRateResp(this);
        result.msgCode_ = msgCode_;
        result.currencyCode_ = currencyCode_;
        result.exchangeCurrencyCode_ = exchangeCurrencyCode_;
        result.price_ = price_;
        result.priceHigh24H_ = priceHigh24H_;
        result.priceLow24H_ = priceLow24H_;
        result.unixTime_ = unixTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.frizo.grpc.api.ExchangeRate.ExchangeRateResp) {
          return mergeFrom((com.frizo.grpc.api.ExchangeRate.ExchangeRateResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.frizo.grpc.api.ExchangeRate.ExchangeRateResp other) {
        if (other == com.frizo.grpc.api.ExchangeRate.ExchangeRateResp.getDefaultInstance()) return this;
        if (!other.getMsgCode().isEmpty()) {
          msgCode_ = other.msgCode_;
          onChanged();
        }
        if (!other.getCurrencyCode().isEmpty()) {
          currencyCode_ = other.currencyCode_;
          onChanged();
        }
        if (!other.getExchangeCurrencyCode().isEmpty()) {
          exchangeCurrencyCode_ = other.exchangeCurrencyCode_;
          onChanged();
        }
        if (!other.getPrice().isEmpty()) {
          price_ = other.price_;
          onChanged();
        }
        if (!other.getPriceHigh24H().isEmpty()) {
          priceHigh24H_ = other.priceHigh24H_;
          onChanged();
        }
        if (!other.getPriceLow24H().isEmpty()) {
          priceLow24H_ = other.priceLow24H_;
          onChanged();
        }
        if (other.getUnixTime() != 0L) {
          setUnixTime(other.getUnixTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.frizo.grpc.api.ExchangeRate.ExchangeRateResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.frizo.grpc.api.ExchangeRate.ExchangeRateResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object msgCode_ = "";
      /**
       * <pre>
       * 000000 成功 99999 失敗
       * </pre>
       *
       * <code>string msgCode = 1;</code>
       * @return The msgCode.
       */
      public java.lang.String getMsgCode() {
        java.lang.Object ref = msgCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 000000 成功 99999 失敗
       * </pre>
       *
       * <code>string msgCode = 1;</code>
       * @return The bytes for msgCode.
       */
      public com.google.protobuf.ByteString
          getMsgCodeBytes() {
        java.lang.Object ref = msgCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 000000 成功 99999 失敗
       * </pre>
       *
       * <code>string msgCode = 1;</code>
       * @param value The msgCode to set.
       * @return This builder for chaining.
       */
      public Builder setMsgCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 000000 成功 99999 失敗
       * </pre>
       *
       * <code>string msgCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgCode() {
        
        msgCode_ = getDefaultInstance().getMsgCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 000000 成功 99999 失敗
       * </pre>
       *
       * <code>string msgCode = 1;</code>
       * @param value The bytes for msgCode to set.
       * @return This builder for chaining.
       */
      public Builder setMsgCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object currencyCode_ = "";
      /**
       * <code>string currencyCode = 2;</code>
       * @return The currencyCode.
       */
      public java.lang.String getCurrencyCode() {
        java.lang.Object ref = currencyCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currencyCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currencyCode = 2;</code>
       * @return The bytes for currencyCode.
       */
      public com.google.protobuf.ByteString
          getCurrencyCodeBytes() {
        java.lang.Object ref = currencyCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currencyCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currencyCode = 2;</code>
       * @param value The currencyCode to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currencyCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currencyCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrencyCode() {
        
        currencyCode_ = getDefaultInstance().getCurrencyCode();
        onChanged();
        return this;
      }
      /**
       * <code>string currencyCode = 2;</code>
       * @param value The bytes for currencyCode to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currencyCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object exchangeCurrencyCode_ = "";
      /**
       * <code>string exchangeCurrencyCode = 3;</code>
       * @return The exchangeCurrencyCode.
       */
      public java.lang.String getExchangeCurrencyCode() {
        java.lang.Object ref = exchangeCurrencyCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          exchangeCurrencyCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string exchangeCurrencyCode = 3;</code>
       * @return The bytes for exchangeCurrencyCode.
       */
      public com.google.protobuf.ByteString
          getExchangeCurrencyCodeBytes() {
        java.lang.Object ref = exchangeCurrencyCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exchangeCurrencyCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string exchangeCurrencyCode = 3;</code>
       * @param value The exchangeCurrencyCode to set.
       * @return This builder for chaining.
       */
      public Builder setExchangeCurrencyCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        exchangeCurrencyCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string exchangeCurrencyCode = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExchangeCurrencyCode() {
        
        exchangeCurrencyCode_ = getDefaultInstance().getExchangeCurrencyCode();
        onChanged();
        return this;
      }
      /**
       * <code>string exchangeCurrencyCode = 3;</code>
       * @param value The bytes for exchangeCurrencyCode to set.
       * @return This builder for chaining.
       */
      public Builder setExchangeCurrencyCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        exchangeCurrencyCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object price_ = "";
      /**
       * <code>string price = 4;</code>
       * @return The price.
       */
      public java.lang.String getPrice() {
        java.lang.Object ref = price_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          price_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string price = 4;</code>
       * @return The bytes for price.
       */
      public com.google.protobuf.ByteString
          getPriceBytes() {
        java.lang.Object ref = price_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          price_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string price = 4;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string price = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        
        price_ = getDefaultInstance().getPrice();
        onChanged();
        return this;
      }
      /**
       * <code>string price = 4;</code>
       * @param value The bytes for price to set.
       * @return This builder for chaining.
       */
      public Builder setPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        price_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object priceHigh24H_ = "";
      /**
       * <code>string priceHigh24h = 5;</code>
       * @return The priceHigh24h.
       */
      public java.lang.String getPriceHigh24H() {
        java.lang.Object ref = priceHigh24H_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          priceHigh24H_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string priceHigh24h = 5;</code>
       * @return The bytes for priceHigh24h.
       */
      public com.google.protobuf.ByteString
          getPriceHigh24HBytes() {
        java.lang.Object ref = priceHigh24H_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          priceHigh24H_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string priceHigh24h = 5;</code>
       * @param value The priceHigh24h to set.
       * @return This builder for chaining.
       */
      public Builder setPriceHigh24H(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        priceHigh24H_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string priceHigh24h = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPriceHigh24H() {
        
        priceHigh24H_ = getDefaultInstance().getPriceHigh24H();
        onChanged();
        return this;
      }
      /**
       * <code>string priceHigh24h = 5;</code>
       * @param value The bytes for priceHigh24h to set.
       * @return This builder for chaining.
       */
      public Builder setPriceHigh24HBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        priceHigh24H_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object priceLow24H_ = "";
      /**
       * <code>string priceLow24h = 6;</code>
       * @return The priceLow24h.
       */
      public java.lang.String getPriceLow24H() {
        java.lang.Object ref = priceLow24H_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          priceLow24H_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string priceLow24h = 6;</code>
       * @return The bytes for priceLow24h.
       */
      public com.google.protobuf.ByteString
          getPriceLow24HBytes() {
        java.lang.Object ref = priceLow24H_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          priceLow24H_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string priceLow24h = 6;</code>
       * @param value The priceLow24h to set.
       * @return This builder for chaining.
       */
      public Builder setPriceLow24H(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        priceLow24H_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string priceLow24h = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPriceLow24H() {
        
        priceLow24H_ = getDefaultInstance().getPriceLow24H();
        onChanged();
        return this;
      }
      /**
       * <code>string priceLow24h = 6;</code>
       * @param value The bytes for priceLow24h to set.
       * @return This builder for chaining.
       */
      public Builder setPriceLow24HBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        priceLow24H_ = value;
        onChanged();
        return this;
      }

      private long unixTime_ ;
      /**
       * <code>int64 unixTime = 7;</code>
       * @return The unixTime.
       */
      public long getUnixTime() {
        return unixTime_;
      }
      /**
       * <code>int64 unixTime = 7;</code>
       * @param value The unixTime to set.
       * @return This builder for chaining.
       */
      public Builder setUnixTime(long value) {
        
        unixTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 unixTime = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnixTime() {
        
        unixTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.gash.grpc.lib.ExchangeRateResp)
    }

    // @@protoc_insertion_point(class_scope:com.gash.grpc.lib.ExchangeRateResp)
    private static final com.frizo.grpc.api.ExchangeRate.ExchangeRateResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.frizo.grpc.api.ExchangeRate.ExchangeRateResp();
    }

    public static com.frizo.grpc.api.ExchangeRate.ExchangeRateResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExchangeRateResp>
        PARSER = new com.google.protobuf.AbstractParser<ExchangeRateResp>() {
      @java.lang.Override
      public ExchangeRateResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExchangeRateResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExchangeRateResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExchangeRateResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.frizo.grpc.api.ExchangeRate.ExchangeRateResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * <pre>
   * The greeting service definition.
   * </pre>
   *
   * Protobuf service {@code com.gash.grpc.lib.ExchangeRateQueryService}
   */
  public static abstract class ExchangeRateQueryService
      implements com.google.protobuf.Service {
    protected ExchangeRateQueryService() {}

    public interface Interface {
      /**
       * <pre>
       * Sends a greeting
       * </pre>
       *
       * <code>rpc getExchangeRate(.com.gash.grpc.lib.ExchangeRateReq) returns (.com.gash.grpc.lib.ExchangeRateResp);</code>
       */
      public abstract void getExchangeRate(
          com.google.protobuf.RpcController controller,
          com.frizo.grpc.api.ExchangeRate.ExchangeRateReq request,
          com.google.protobuf.RpcCallback<com.frizo.grpc.api.ExchangeRate.ExchangeRateResp> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new ExchangeRateQueryService() {
        @java.lang.Override
        public  void getExchangeRate(
            com.google.protobuf.RpcController controller,
            com.frizo.grpc.api.ExchangeRate.ExchangeRateReq request,
            com.google.protobuf.RpcCallback<com.frizo.grpc.api.ExchangeRate.ExchangeRateResp> done) {
          impl.getExchangeRate(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getExchangeRate(controller, (com.frizo.grpc.api.ExchangeRate.ExchangeRateReq)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.frizo.grpc.api.ExchangeRate.ExchangeRateReq.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.frizo.grpc.api.ExchangeRate.ExchangeRateResp.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <pre>
     * Sends a greeting
     * </pre>
     *
     * <code>rpc getExchangeRate(.com.gash.grpc.lib.ExchangeRateReq) returns (.com.gash.grpc.lib.ExchangeRateResp);</code>
     */
    public abstract void getExchangeRate(
        com.google.protobuf.RpcController controller,
        com.frizo.grpc.api.ExchangeRate.ExchangeRateReq request,
        com.google.protobuf.RpcCallback<com.frizo.grpc.api.ExchangeRate.ExchangeRateResp> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.frizo.grpc.api.ExchangeRate.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getExchangeRate(controller, (com.frizo.grpc.api.ExchangeRate.ExchangeRateReq)request,
            com.google.protobuf.RpcUtil.<com.frizo.grpc.api.ExchangeRate.ExchangeRateResp>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.frizo.grpc.api.ExchangeRate.ExchangeRateReq.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.frizo.grpc.api.ExchangeRate.ExchangeRateResp.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.frizo.grpc.api.ExchangeRate.ExchangeRateQueryService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getExchangeRate(
          com.google.protobuf.RpcController controller,
          com.frizo.grpc.api.ExchangeRate.ExchangeRateReq request,
          com.google.protobuf.RpcCallback<com.frizo.grpc.api.ExchangeRate.ExchangeRateResp> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.frizo.grpc.api.ExchangeRate.ExchangeRateResp.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.frizo.grpc.api.ExchangeRate.ExchangeRateResp.class,
            com.frizo.grpc.api.ExchangeRate.ExchangeRateResp.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.frizo.grpc.api.ExchangeRate.ExchangeRateResp getExchangeRate(
          com.google.protobuf.RpcController controller,
          com.frizo.grpc.api.ExchangeRate.ExchangeRateReq request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.frizo.grpc.api.ExchangeRate.ExchangeRateResp getExchangeRate(
          com.google.protobuf.RpcController controller,
          com.frizo.grpc.api.ExchangeRate.ExchangeRateReq request)
          throws com.google.protobuf.ServiceException {
        return (com.frizo.grpc.api.ExchangeRate.ExchangeRateResp) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.frizo.grpc.api.ExchangeRate.ExchangeRateResp.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:com.gash.grpc.lib.ExchangeRateQueryService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gash_grpc_lib_ExchangeRateReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gash_grpc_lib_ExchangeRateReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gash_grpc_lib_ExchangeRateResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gash_grpc_lib_ExchangeRateResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ExchangeRate.proto\022\021com.gash.grpc.lib\"" +
      "E\n\017ExchangeRateReq\022\024\n\014currencyCode\030\001 \001(\t" +
      "\022\034\n\024exchangeCurrencyCode\030\002 \001(\t\"\243\001\n\020Excha" +
      "ngeRateResp\022\017\n\007msgCode\030\001 \001(\t\022\024\n\014currency" +
      "Code\030\002 \001(\t\022\034\n\024exchangeCurrencyCode\030\003 \001(\t" +
      "\022\r\n\005price\030\004 \001(\t\022\024\n\014priceHigh24h\030\005 \001(\t\022\023\n" +
      "\013priceLow24h\030\006 \001(\t\022\020\n\010unixTime\030\007 \001(\0032x\n\030" +
      "ExchangeRateQueryService\022\\\n\017getExchangeR" +
      "ate\022\".com.gash.grpc.lib.ExchangeRateReq\032" +
      "#.com.gash.grpc.lib.ExchangeRateResp\"\000B\031" +
      "\n\022com.frizo.grpc.apiP\000\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_gash_grpc_lib_ExchangeRateReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gash_grpc_lib_ExchangeRateReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gash_grpc_lib_ExchangeRateReq_descriptor,
        new java.lang.String[] { "CurrencyCode", "ExchangeCurrencyCode", });
    internal_static_com_gash_grpc_lib_ExchangeRateResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gash_grpc_lib_ExchangeRateResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gash_grpc_lib_ExchangeRateResp_descriptor,
        new java.lang.String[] { "MsgCode", "CurrencyCode", "ExchangeCurrencyCode", "Price", "PriceHigh24H", "PriceLow24H", "UnixTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
