// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.frizo.grpc.lib;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_frizo_grpc_lib_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_frizo_grpc_lib_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_frizo_grpc_lib_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_frizo_grpc_lib_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\022\022com.frizo.grpc.lib\"\034\n\014H" +
      "elloRequest\022\014\n\004name\030\001 \001(\t\"\035\n\nHelloReply\022" +
      "\017\n\007message\030\001 \001(\t2[\n\tMyService\022N\n\010SayHell" +
      "o\022 .com.frizo.grpc.lib.HelloRequest\032\036.co" +
      "m.frizo.grpc.lib.HelloReply\"\000B*\n\022com.fri" +
      "zo.grpc.libB\017HelloWorldProtoP\001\210\001\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_frizo_grpc_lib_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_frizo_grpc_lib_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_frizo_grpc_lib_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_frizo_grpc_lib_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_frizo_grpc_lib_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_frizo_grpc_lib_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
